// This file is intended to serve as the single source of truth for all app level configurations.

const APP_CONFIG = {
  categories: [
    {
      name: "Groceries",
      icon: "cart",
      subcategories: [
        { name: "Fruits", icon: "apple" },
        { name: "Vegetables", icon: "leaf" },
      ],
    },
    {
      name: "Transport",
      icon: "car",
      subcategories: [
        { name: "Fuel", icon: "gas-station" },
        { name: "Taxi", icon: "taxi" },
      ],
    },
    {
      name: "Entertainment",
      icon: "movie",
      subcategories: [
        { name: "Movies", icon: "film" },
        { name: "Games", icon: "gamepad" },
      ],
    },
    { name: "Rent", icon: "home" },
    { name: "Utilities", icon: "flash" },
  ],
  currencies: [
    {
      title: "INR",
      value: "₹",
    },
    {
      title: "USD",
      value: "$",
    },
  ],
  dateFormats: [
    {
      title: "DD-MMM-YYYY",
      value: "DD-MMM-YYYY",
    },
    {
      title: "YYYY-MM-DD",
      value: "YYYY-MM-DD",
    },
  ],
  dayNames: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  monthNames: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  decimalPlaces: 2,
  font: {
    family: "IBM Plex Serif",
  },
  icons: [
    "ambulance",
    "autorenew",
    "bag-suitcase",
    "bank",
    "beach",
    "bell-ring",
    "book-open-variant-outline",
    "broom",
    "cake-variant",
    "camera",
    "car",
    "car-brake-parking",
    "car-seat",
    "carrot",
    "cart",
    "cash",
    "cash-refund",
    "cellphone",
    "coffee",
    "cog",
    "cookie",
    "cow",
    "cube-outline",
    "cupcake",
    "dice-multiple",
    "diamond-stone",
    "doctor",
    "flash",
    "food-apple",
    "fridge-outline",
    "gamepad-variant",
    "gas-station",
    "gavel",
    "gift",
    "gold",
    "google",
    "hamburger",
    "hammer-wrench",
    "hand-heart",
    "hand-wash",
    "hands-pray",
    "headphones",
    "heart",
    "home",
    "ice-cream",
    "lamp",
    "laptop",
    "lipstick",
    "meditation",
    "microscope",
    "movie",
    "movie-open",
    "music",
    "necklace",
    "notebook-outline",
    "pen",
    "pill",
    "printer",
    "ring",
    "scan-helper",
    "screwdriver",
    "shield-plus",
    "shoe-formal",
    "shopping",
    "silverware",
    "silverware-fork-knife",
    "soccer",
    "sofa",
    "star",
    "stethoscope",
    "taxi",
    "television",
    "trophy",
    "tshirt-crew",
    "water",
    "watch",
    "weight-lifter",
    "wall",
  ],
  languages: [
    {
      title: "English",
      value: "en",
    },
  ],
  numberFormats: [
    {
      title: "Indian Format (en-IN)",
      value: "en-IN",
    },
    {
      title: "US Format (en-US)",
      value: "en-US",
    },
  ],
  routes: {
    home: "/",
    settings: "/settings",
  },
  storage: {
    catgories: "categories",
    storageAppData: "appData",
    storageCurrencyUnit: "currencyUnit",
    storageDateFormat: "dateFormat",
    storageLanguage: "language",
    storageNumberFormat: "numberFormat",
  },
  yearRange: 5,
};

export default APP_CONFIG;
